### ISSUE TITLE
Failure to parse manifest file

### ISSUE THREAD

**Issue by ndmitchell** [cmyr/cargo-instruments#39]
Given:

```
cargo-features = ['named-profiles']

[workspace]
members = [
    "foo",
]
```

I get the error:

```
ndmitchell@ndmitchell-mbp buck2 % cargo instruments
failed to parse manifest at `/Users/ndmitchell/fbsource/fbcode/buck2/Cargo.toml`
```

It would be great if this tool could properly parse such manifest files.

**Comment by cmyr** [comment]
`cargo check` also fails to parse this manifest.

More specifically, my manifest is:

```toml
[package]
name = "test-instruments-parse-issue"
version = "0.1.0"
authors = ["Colin Rofls <colin@cmyr.net>"]
edition = "2018"

cargo-features = ['named-profiles']

[workspace]
members = [
    "inner",
]
```

and my package structure is,

```
test-instruments-parse-issue
├── Cargo.toml
└── inner
    ├── Cargo.toml
    └── src
        └── main.rs

2 directories, 3 files
```


I would like to handle workspaces better, but I need more information in this particular case.

**Comment by ndmitchell** [comment]
Sorry for taking so long to get back to you. I reinstalled everything with a newer toolchain, and recompiled cargo-instruments and it worked this time - so I assume a newer Cargo dependency or similar fixed it?

In general, for better support for workspaces, allowing the user to be in the root and run `--bin=whatever_binary` rather than changing directory to the inner Cargo.toml would be super useful.

**Comment by cmyr** [comment]
I agree that would be a nice improvement.

**Comment by tizee** [comment]
> 

Here is my demonstration.

```
.
├── Cargo.lock
├── Cargo.toml
├── bar
│   ├── Cargo.toml
│   ├── benches
│   │   └── my_bench.rs
│   └── src
│       └── main.rs
├── foo
│   ├── Cargo.toml
│   ├── benches
│   │   └── my_bench.rs
│   └── src
│       └── main.rs
├── rust-toolchain.toml
└── src
    └── main.rs

7 directories, 10 files
```

The manifest is like:
```toml
[package]
name = "cargo-instruments-workspace-issue"
version = "0.1.0"
edition = "2021"
# cargo-features = ['named-profiles']

[workspace]
members = ["foo", "bar"]
```

Only comment out `cargo-features = ['named-profiles']` can `cargo check` work.

It could also applies to manifest with only `[workspace]` block like this:

```toml
[workspace]
members = ["foo", "bar"]
```

**Comment by Philogy** [comment]
Also having this issue but `cargo check` passes with no issues.

**`Cargo.toml`**
```toml
[package]
name = "scramble-string"
version = "0.1.0"
edition = "2024"

[dependencies]

[profile.profiling]
inherits = "release"
debug = true
```

**`Tool versions`**
```
>> cargo --version
cargo 1.84.1 (66221abde 2024-11-19)
>> cargo instruments --version
cargo-instruments 0.4.10
```

**Comment by cmyr** [comment]
I need to update the crate to support newer versions of cargo, will look at that now

**Comment by cmyr** [comment]
@Philogy just released 0.4.11, try that and see if it works?

**Comment by romac** [comment]
I am seeing the same issue with cargo-instruments 0.4.11 on Rust 1.85.0 with the following `Cargo.toml`:

```toml
[package]
name = "foobar"
version = "0.1.0"
edition = "2024"
```
